# Generated by Django 3.0.5 on 2020-04-23 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-dateTime']},
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='date',
            new_name='dateTime',
        ),
    ]
