# Generated by Django 3.0.5 on 2020-04-23 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200423_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='dateTime',
            field=models.DateTimeField(),
        ),
    ]
